import { RobinhoodEvmAsset, RobinhoodTokenType } from '../types'

/**
 * EVM Asset Metadata (Display Information Only)
 *
 * NOTE: Deposit addresses are fetched dynamically from Coinbase Prime
 * This file only contains static metadata (icons, descriptions, etc.)
 *
 * For static fallback addresses, see: evm-assets-static.ts
 */

/**
 * EVM Asset Metadata Registry
 * Static display information for each asset
 */
export const EVM_ASSETS: Record<string, RobinhoodEvmAsset> = {
  ETH: {
    symbol: 'ETH',
    name: 'Ethereum',
    description: 'Smart contract platform and cryptocurrency',
    network: 'ETHEREUM',
    chainId: 1,
    category: 'layer1',
    icon: 'eth.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880',
    decimals: 18,
    enabled: true,
    featured: true,
    popularity: 100,
    sortOrder: 2,
    type: RobinhoodTokenType.EvmToken,
  },

  AVAX: {
    symbol: 'AVAX',
    name: 'Avalanche',
    description: 'Fast, low-cost blockchain platform',
    network: 'AVALANCHE',
    chainId: 43114,
    category: 'layer1',
    icon: 'avax.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png?1670992574',
    decimals: 18,
    enabled: true,
    popularity: 70,
    sortOrder: 10,
    type: RobinhoodTokenType.EvmToken,
  },

  ETC: {
    symbol: 'ETC',
    name: 'Ethereum Classic',
    description: 'Original Ethereum blockchain',
    network: 'ETHEREUM_CLASSIC',
    chainId: 61,
    category: 'layer1',
    icon: 'etc.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/453/small/ethereum-classic-logo.png?1547034169',
    decimals: 18,
    enabled: true,
    popularity: 40,
    sortOrder: 14,
    type: RobinhoodTokenType.EvmToken,
  },

  // Layer 2 - Enabled if Robinhood supports
  MATIC: {
    symbol: 'MATIC',
    name: 'Polygon',
    description: 'Ethereum scaling solution',
    network: 'POLYGON',
    chainId: 137,
    category: 'layer2',
    icon: 'matic.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/4713/small/polygon.png?1698233684',
    decimals: 18,
    enabled: true,
    popularity: 75,
    sortOrder: 11,
    type: RobinhoodTokenType.EvmToken,
  },

  ARB: {
    symbol: 'ARB',
    name: 'Arbitrum',
    description: 'Ethereum Layer 2 scaling solution',
    network: 'ARBITRUM',
    chainId: 42161,
    category: 'layer2',
    icon: 'arb.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg?1680097630',
    decimals: 18,
    enabled: true,
    popularity: 70,
    sortOrder: 12,
    type: RobinhoodTokenType.EvmToken,
  },

  OP: {
    symbol: 'OP',
    name: 'Optimism',
    description: 'Ethereum Layer 2 optimistic rollup',
    network: 'OPTIMISM',
    chainId: 10,
    category: 'layer2',
    icon: 'op.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png?1660904599',
    decimals: 18,
    enabled: true,
    popularity: 68,
    sortOrder: 13,
    type: RobinhoodTokenType.EvmToken,
  },

  ZORA: {
    symbol: 'ZORA',
    name: 'Zora',
    description: 'NFT marketplace and Layer 2 network',
    network: 'ZORA',
    chainId: 7777777,
    category: 'layer2',
    icon: 'zora.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/34782/small/zora.png?1706002107',
    decimals: 18,
    enabled: true,
    popularity: 45,
    sortOrder: 14,
    type: RobinhoodTokenType.EvmToken,
  },

  // Stablecoins
  USDC: {
    symbol: 'USDC',
    name: 'USD Coin',
    description: 'US Dollar stablecoin',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    category: 'stablecoin',
    icon: 'usdc.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png?1547042389',
    decimals: 6,
    enabled: true,
    featured: true,
    popularity: 95,
    sortOrder: 4,
    type: RobinhoodTokenType.EvmToken,
  },

  // DeFi Tokens
  AAVE: {
    symbol: 'AAVE',
    name: 'Aave',
    description: 'DeFi lending protocol token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    category: 'defi',
    icon: 'aave.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png?1601374110',
    decimals: 18,
    enabled: true,
    popularity: 60,
    sortOrder: 20,
    type: RobinhoodTokenType.EvmToken,
  },

  UNI: {
    symbol: 'UNI',
    name: 'Uniswap',
    description: 'Decentralized exchange token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    category: 'defi',
    icon: 'uni.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/12504/small/uni.jpg?1687143398',
    decimals: 18,
    enabled: true,
    popularity: 65,
    sortOrder: 21,
    type: RobinhoodTokenType.EvmToken,
  },

  LINK: {
    symbol: 'LINK',
    name: 'Chainlink',
    description: 'Decentralized oracle network',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
    category: 'defi',
    icon: 'link.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png?1547034700',
    decimals: 18,
    enabled: true,
    popularity: 68,
    sortOrder: 22,
    type: RobinhoodTokenType.EvmToken,
  },

  COMP: {
    symbol: 'COMP',
    name: 'Compound',
    description: 'DeFi lending protocol token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0xc00e94Cb662C3520282E6f5717214004A7f26888',
    category: 'defi',
    icon: 'comp.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/10775/small/COMP.png?1592625425',
    decimals: 18,
    enabled: true,
    popularity: 55,
    sortOrder: 23,
    type: RobinhoodTokenType.EvmToken,
  },

  CRV: {
    symbol: 'CRV',
    name: 'Curve DAO',
    description: 'DeFi stablecoin exchange token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0xD533a949740bb3306d119CC777fa900bA034cd52',
    category: 'defi',
    icon: 'crv.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/12124/small/Curve.png?1597369484',
    decimals: 18,
    enabled: true,
    popularity: 50,
    sortOrder: 24,
    type: RobinhoodTokenType.EvmToken,
  },

  ONDO: {
    symbol: 'ONDO',
    name: 'Ondo',
    description: 'Institutional-grade DeFi protocol',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0xfAbA6f8e4a5E8Ab82F62fe7C39859FA577269BE3',
    category: 'defi',
    icon: 'ondo.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/26580/small/ONDO.png?1696525656',
    decimals: 18,
    enabled: true,
    popularity: 45,
    sortOrder: 25,
    type: RobinhoodTokenType.EvmToken,
  },

  // Meme Coins
  SHIB: {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    description: 'Ethereum-based meme token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    category: 'meme',
    icon: 'shib.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png?1622619446',
    decimals: 18,
    enabled: true,
    popularity: 72,
    sortOrder: 31,
    type: RobinhoodTokenType.EvmToken,
  },

  PEPE: {
    symbol: 'PEPE',
    name: 'Pepecoin',
    description: 'Internet meme cryptocurrency',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0x6982508145454Ce325dDbE47a25d4ec3d2311933',
    category: 'meme',
    icon: 'pepe.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/29850/small/pepe-token.jpeg?1682922725',
    decimals: 18,
    enabled: true,
    popularity: 60,
    sortOrder: 32,
    type: RobinhoodTokenType.EvmToken,
  },

  FLOKI: {
    symbol: 'FLOKI',
    name: 'Floki',
    description: 'Community-driven meme token',
    network: 'ETHEREUM',
    chainId: 1,
    contractAddress: '0xcf0C122c6b73ff809C693DB761e7BaeBe62b6a2E',
    category: 'meme',
    icon: 'floki.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/16746/small/PNG_image.png?1643184642',
    decimals: 9,
    enabled: true,
    popularity: 55,
    sortOrder: 33,
    type: RobinhoodTokenType.EvmToken,
  },

  VIRTUAL: {
    symbol: 'VIRTUAL',
    name: 'Virtuals Protocol',
    description: 'Virtual reality protocol token',
    network: 'ETHEREUM',
    chainId: 1,
    category: 'other',
    icon: 'virtual.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/41486/standard/virtual.png?1728529786',
    decimals: 18,
    enabled: true,
    popularity: 45,
    sortOrder: 41,
    type: RobinhoodTokenType.EvmToken,
  },

  WLFI: {
    symbol: 'WLFI',
    name: 'World Liberty Financial',
    description: 'DeFi financial protocol',
    network: 'ETHEREUM',
    chainId: 1,
    category: 'other',
    icon: 'wlfi.svg',
    logoUrl: 'https://assets.coingecko.com/coins/images/42721/standard/WLFI_Token.png?1732760729',
    decimals: 18,
    enabled: true,
    popularity: 40,
    sortOrder: 42,
    type: RobinhoodTokenType.EvmToken,
  },
}
